Minimal upgrades of requests, urllib3 and reverse dependencies
Addresses:

    >>> import urllib3
    ...
    ModuleNotFoundError: No module named 'urllib3.packages.six'

(See also: https://github.com/urllib3/urllib3/issues/1518)